web:
    image: nginx:1.7.9
    volumes:
        - ./dist:/usr/share/nginx/html
        - ./conf/nginx-dev.conf:/etc/nginx/nginx.conf
    ports:
        - "80:80"
    links:
        - ws
        - db

ws:
    image: ksahnine/ratp-rest-api:1.0
    links:
        - db
    ports:
        - "8080:8080"

db:
    image: fedora/couchdb
    ports:
        - "5984:5984"
